services:
  mysql:
    image: mysql:8.0
    container_name: database_container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: sl_university_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: ${DB_APP_PASS}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    image: akila99/sl-university-backend:latest
    container_name: sl-university-backend
    restart: always
    environment:
      DB_URL: jdbc:mysql://mysql:3306/sl_university_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USER: app_user
      DB_PASSWORD: ${DB_APP_PASS}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: http://${EC2_PUBLIC_IP}:3000
      BASE_URL: http://${EC2_PUBLIC_IP}:8080/api
      JWT_ACCESS_MS: 86400000
      JWT_REFRESH_MS: 1209600000
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - appnet

  frontend:
    image: akila99/sl-university-frontend:latest
    container_name: sl-university-frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://${EC2_PUBLIC_IP}:8080/api
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - appnet

volumes:
  db-data:

networks:
  appnet:
