version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: database_container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: sl_university_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: ${DB_APP_PASS}
    networks:
      - appnet
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ${DOCKER_USERNAME}/sl-university-backend:latest
    build:
      context: ./SlUniversityBackend
      dockerfile: Dockerfile
    container_name: sl-university-backend
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/sl_university_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USER: app_user
      DB_PASSWORD: ${DB_APP_PASS}
      FRONTEND_URL: http://${EC2_PUBLIC_IP}:3000
      BASE_URL: http://localhost:8080/api
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_MS: 86400000
      JWT_REFRESH_MS: 1209600000
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    networks:
      - appnet

  frontend:
    image: ${DOCKER_USERNAME}/sl-university-frontend:latest
    build:
      context: ./sluniversityfrontend
      dockerfile: Dockerfile
    container_name: sl-university-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://${EC2_PUBLIC_IP}:8080/api
      NODE_ENV: production
    depends_on:
      - backend
    networks:
      - appnet

volumes:
  db-data:

networks:
  appnet:
    driver: bridge
