name: 1. Build and Push Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend image
        working-directory: ./SlUniversityBackend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sl-university-backend:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/sl-university-backend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/sl-university-backend:latest

      - name: Build frontend image
        working-directory: ./sluniversityfrontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sl-university-frontend:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/sl-university-frontend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/sl-university-frontend:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sl-university-backend:latest

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sl-university-frontend:latest
